language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: false
script:
- nosetests
after_success:
- codecov
deploy:
  provider: pypi
  user: fabian-rump
  password:
    secure: "I1+vHldUwZimGvxrSoblHn4gjXncfoyG33Ke2bR9JjdC+NfHdFmwdeAor/PDR3nXSxJM5e9vdLpvMOUQgRMwS5PdYHD4HmnIFR2BLWnvnb+2EeUylqfIMpblXF62lgUVLDIaO3GsJ+xbH9JGOpzPPkASEM+mD5k9znAFma/5i3W1Pk3DqCKKzFV25mfOpDzZ0yicZG+yu3bhntgpb+evUdls5QnkhKbCK4V7Ywyw550JN/Ji8BGEm4G+g9xPfjYgQ/CTtP7Px9eg+x6Mv9lFx9Hh3MCFOh1LxMPYrLF2iEeu4MZdRk/25h2jpt3RMZWDVPdJjjVnI2KhK5ll56eyasEzQOoBIiR8rI7588n0dGOzYPfRoz1IBhxSi584vTfynT2geD8dLI348F0szg4ec2NsHx0Ox6SrV3CYri7W5AKwylM+jLbkAU2zlBFZdTKX2+Wn5EJj+cVjOuycm4Ar+QCvyrAiPRPJw21HK/qz3lpfaO6xcITmq6BgBybno7nM1f8Lb8AtO6LEPQlcjhOgJ5yaTJeD6GWnZ+zVFo3VL2Ip/tEgRUU9mpAmOjkkfc33JjRDej7y815dISJqYoTtNxKvxM9UxQSy8worg0CDE9EpmN1cehC4kpUhockuRJCAGb+wGSfAZBk2c71ys1+Kz+fBWp0AF7m89Eyr7n/ECqg="
  on:
    tags: true
    python: '3.6'
